---
# Calamares welcome module
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true

requirements:
    requiredStorage: 10.0
    requiredRam: 1.0
    internetCheckUrl: https://github.com
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
